version: 0.2

env:
  variables:
    ENVIRONMENT: "dev"
    IMAGE_NAME: "dev-padre-swsoc-docker-lambda-base"

phases:
  pre_build:
    commands:
      - |
        echo Logging in to Amazon ECR...
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w5r9l1c8
        if git describe --tags --exact-match > /dev/null 2>&1; then
          echo "This is a tag push event"
          ENVIRONMENT="prod"
          IMAGE_NAME="padre-swsoc-docker-lambda-base"
          GIT_TAG=`git describe --tags --exact-match`
        elif [[ "${CDK_ENVIRONMENT}" == "PRODUCTION" ]]; then
          echo "This is a production environment"
          ENVIRONMENT="prod"
          IMAGE_NAME="padre-swsoc-docker-lambda-base"
          GIT_TAG=`date -u +"%Y%m%d%H%M%S"`
        else
          echo "This is a development environment"
          GIT_TAG=`date -u +"%Y%m%d%H%M%S"`
        fi

  build:
    commands:
      - |
        echo Build started on `date`
        echo Building the Docker image...          
        docker build -t ${IMAGE_NAME}:${ENVIRONMENT}-${GIT_TAG} .
        docker tag ${IMAGE_NAME}:${ENVIRONMENT}-${GIT_TAG} public.ecr.aws/w5r9l1c8/${IMAGE_NAME}:${ENVIRONMENT}-${GIT_TAG}
        docker tag ${IMAGE_NAME}:${ENVIRONMENT}-${GIT_TAG} public.ecr.aws/w5r9l1c8/${IMAGE_NAME}:latest

        echo Pushing the Docker image...
        docker push public.ecr.aws/w5r9l1c8/${IMAGE_NAME}:${ENVIRONMENT}-${GIT_TAG}
        docker push public.ecr.aws/w5r9l1c8/${IMAGE_NAME}:latest
        PUBLIC_ECR_REPO=public.ecr.aws/w5r9l1c8/${IMAGE_NAME}:${ENVIRONMENT}-${GIT_TAG}
      - echo "Starting Lambda Function builds..."
      - aws codebuild start-build --project-name arn:aws:codebuild:us-east-1:351967858401:project/build_padre_sdc_aws_sorting_lambda --environment-variables-override name=CDK_ENVIRONMENT,value=$CDK_ENVIRONMENT,type=PLAINTEXT
      - aws codebuild start-build --project-name arn:aws:codebuild:us-east-1:351967858401:project/build_padre_sdc_aws_processing_lambda --environment-variables-override name=CDK_ENVIRONMENT,value=$CDK_ENVIRONMENT,type=PLAINTEXT
      - aws codebuild start-build --project-name arn:aws:codebuild:us-east-1:351967858401:project/build_padre_sdc_aws_artifact_lambda --environment-variables-override name=CDK_ENVIRONMENT,value=$CDK_ENVIRONMENT,type=PLAINTEXT
      - aws codebuild start-build --project-name arn:aws:codebuild:us-east-1:351967858401:project/build_padre_sdc_aws_concating_lambda --environment-variables-override name=CDK_ENVIRONMENT,value=$CDK_ENVIRONMENT,type=PLAINTEXT 
       
  post_build:
    commands:
      - echo Build completed on `date`
 